name: Model Training

on:
  push:
    branches:
      - master

jobs:
  build:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: 'projects/882200096888/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-actions@forecasting-fantasy-football.iam.gserviceaccount.com'
    - id: deploy
      uses: 'google-github-actions/deploy-appengine@v0'
      working_directory: ./app
