name: Model Training

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Train models
      run: |
        python -m scripts.train_points_model --horizon 1 --position GK --outdir ./models
        python -m scripts.train_points_model --horizon 1 --position DEF --outdir ./models
        python -m scripts.train_points_model --horizon 1 --position MID --outdir ./models
        python -m scripts.train_points_model --horizon 1 --position FWD --outdir ./models
        python -m scripts.train_points_model --horizon 2 --position GK --outdir ./models
        python -m scripts.train_points_model --horizon 2 --position DEF --outdir ./models
        python -m scripts.train_points_model --horizon 2 --position MID --outdir ./models
        python -m scripts.train_points_model --horizon 2 --position FWD --outdir ./models
        tar -czvf models.tar.gz ./models
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: models
        path: models.tar.gz
        retention-days: 30


