name: Model Training

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Train models
      run: |
        python -m scripts.train_all --horizon 4 --outfile preds.csv
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: preds
        path: preds.csv
        retention-days: 30


